# Change these first
owner: Dicloxacillin # Your GitHub organization or username, where this repository lives
repo: ucportals # The name of this repository

sites:
  - name: Skingenes
    url: http://www.skingenes.net
  - name: U54 Data Portal
    url: https://ucightf1.biochem.uci.edu
  - name: Google
    url: https://www.google.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /ucportals
  logoUrl: https://brand.uci.edu/master-branding/primary-logos/_img/UCI_primarylogo_printblue.png
  name: Upptime
  introTitle: "Welcome to the UCI Genomics Research and Technology Hub server status site."
  introMessage: If you have any questions or concerns about the status of the server, please contact Ivan Chang at iychang@uci.edu. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
